services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
  chronograf:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - '8888:8888'
    volumes:
      - ./chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - BOLT_PATH=/var/lib/chronograf/chronograf-v1.db
      - HTPASSWD=/var/lib/chronograf/.htpasswd


